name: First github action
on: [push]
jobs: 
  build-project:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "hello world"
      - run: echo "building project"
  listing:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
 
