name: First github action
on: [push]
jobs: 
  listing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tree
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
      - name : get version
        run: node --version
 
